apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkconnect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkconnect
  template:
    metadata:
      labels:
        app: nkconnect
    spec:
      containers:
        - name: nkconnect-container
          image: iainttho/nk-connect:latest # Update the image name and tag
          ports:
            - containerPort: 9096 # Update the container port

---
apiVersion: v1
kind: Service
metadata:
  name: nkconnect-service
spec:
  selector:
    app: nkconnect
  ports:
    - protocol: TCP
      port: 9096
      # targetPort: 9096 # Update the target port
      nodePort: 30808 # Specify the NodePort here
  type: NodePort
