apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkDataProvider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkDataProvider
  template:
    metadata:
      labels:
        app: nkDataProvider
    spec:
      containers:
        - name: nkDataProvider-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data-pv
              mountPath: /var/lib/postgresql/data
            - name: postgres-logs-pv
              mountPath: /var/log/postgresql
      volumes:
        - name: postgres-data-pv # Volume name matching volumeMounts
          persistentVolumeClaim:
            claimName: postgres-data-pvc # Claim name for PersistentVolumeClaim
        - name: postgres-logs-pv # Volume name matching volumeMounts
          persistentVolumeClaim:
            claimName: postgres-logs-pvc # Claim name for PersistentVolumeClaim

---
apiVersion: v1
kind: Service
metadata:
  name: nkDataProvider-service
spec:
  selector:
    app: nkDataProvider
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/Users/thonguyenkhac/workspaces/massy_rendering/k8s-deployement/volumes/database/data" # Update this path to your local data directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/Users/thonguyenkhac/workspaces/massy_rendering/k8s-deployement/volumes/database/logs" # Update this path to your local logs directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
